<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Player;

class PlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $players = [
            // ATALANTA
            [
                "first_name" => "Marco",
                "last_name" => "Carnesecchi",
                "date_of_birth" => '2000-07-01',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 20.00,
                "fav_foot" => "Destro",
                "height" => '1.91',
                "img" => "https://img.legaseriea.it/vimages/66cf2fc8/CRNMR1.png?webp&q=100&ch=840&size=609x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Rafael",
                "last_name" => "Toloi",
                "date_of_birth" => '1990-10-10',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 1.50,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66cf2fca/BLLZX.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Raoul",
                "last_name" => "Bellanova",
                "date_of_birth" => '2000-05-17',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 22.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf2fb4/BLLVRL.png?webp&q=100&ch=840&size=483x-+",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Isak",
                "last_name" => "Hien",
                "date_of_birth" => '1999-01-13',
                "role" => "Difensore",
                "nationality" => "Svezia",
                "market_value" => 30.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66cf2fae/HIENIS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Berat",
                "last_name" => "Djimsiti",
                "date_of_birth" => '1993-02-19',
                "role" => "Difensore",
                "nationality" => "Albania",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66cf2fe7/DJMBR.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Sead",
                "last_name" => "Kolasinac",
                "date_of_birth" => '1993-06-20',
                "role" => "Difensore",
                "nationality" => "Bosnia-Erzegovina",
                "market_value" => 10.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf2fb1/HQZLT.png?webp&q=100&ch=840&size=499.5x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Giorgio",
                "last_name" => "Scalvini",
                "date_of_birth" => '2003-12-11',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 45.00,
                "fav_foot" => "Destro",
                "height" => "1.94",
                "img" => "https://img.legaseriea.it/vimages/66cf2fc2/SCLGRG.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Juan",
                "last_name" => "Cuadrado",
                "date_of_birth" => '1988-05-26',
                "role" => "Centrocampista",
                "nationality" => "Colombia",
                "market_value" => 1.00,
                "fav_foot" => "Destro",
                "height" => "1.76",
                "img" => "https://img.legaseriea.it/vimages/66db1bf7/CDRJN.png?webp&q=100&ch=840&size=481.5x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Mario",
                "last_name" => "Pašalić",
                "date_of_birth" => '1995-02-09',
                "role" => "Centrocampista",
                "nationality" => "Croazia",
                "market_value" => 13.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf2fda/PSLMR.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "José",
                "last_name" => "Ederson",
                "date_of_birth" => '1999-07-07',
                "role" => "Centrocampista",
                "nationality" => "Brasile",
                "market_value" => 50.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf2fdf/EDERSO.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Marten",
                "last_name" => "De Roon",
                "date_of_birth" => '1991-03-29',
                "role" => "Centrocampista",
                "nationality" => "Olanda",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66cf2fcc/DRNMR.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Matteo",
                "last_name" => "Ruggeri",
                "date_of_birth" => '2002-07-11',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 20.00,
                "fav_foot" => "Sinistro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66cf2fe1/RGGMTT.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Lazar",
                "last_name" => "Samardžić",
                "date_of_birth" => '2002-02-24',
                "role" => "Centrocampista",
                "nationality" => "Serbia",
                "market_value" => 20.00,
                "fav_foot" => "Sinistro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/66cf2fb1/SMRLZR.png?webp&q=100&ch=840&size=508.5x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Marco",
                "last_name" => "Brescianini",
                "date_of_birth" => '2000-01-20',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 8.00,
                "fav_foot" => "Sinistro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf2fc3/BRSMR1.png?webp&q=100&ch=840&size=520.5x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Davide",
                "last_name" => "Zappacosta",
                "date_of_birth" => '1992-06-11',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.82",
                "img" => "https://img.legaseriea.it/vimages/66cf2fd6/ZPPDV.png?webp&q=100&ch=840&size=529.5x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Ademola",
                "last_name" => "Lookman",
                "date_of_birth" => '1997-10-20',
                "role" => "Attaccante",
                "nationality" => "Nigeria",
                "market_value" => 55.00,
                "fav_foot" => "Destro",
                "height" => "1.74",
                "img" => "https://img.legaseriea.it/vimages/66cf2fd4/LKMDML.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Charles",
                "last_name" => "De Ketelaere",
                "date_of_birth" => '2001-03-10',
                "role" => "Attaccante",
                "nationality" => "Belgio",
                "market_value" => 38.00,
                "fav_foot" => "Sinistro",
                "height" => "1.92",
                "img" => "https://img.legaseriea.it/vimages/66cf2fd4/DKTRLS.png?webp&q=100&ch=840&size=606x-",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            [
                "first_name" => "Mateo",
                "last_name" => "Retegui",
                "date_of_birth" => '1999-04-29',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 35.00,
                "fav_foot" => "Destro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/66cf2fe0/RETEGU.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 5,
                "coach_id" => 20,
            ],
            // BOLOGNA
            [
                "first_name" => "Lucasz",
                "last_name" => "Skorupski",
                "date_of_birth" => '1991-05-05',
                "role" => "Portiere",
                "nationality" => "Polonia",
                "market_value" => 2.50,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66db1bcc/SKRLZ.png?webp&q=100&ch=840&size=468x-",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Emil",
                "last_name" => "Hol",
                "date_of_birth" => '2000-05-13',
                "role" => "Difensore",
                "nationality" => "Svezia",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66cf4bd5/HOLMEM.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Charalampos",
                "last_name" => "Lykogiannis",
                "date_of_birth" => '1993-10-22',
                "role" => "Difensore",
                "nationality" => "Grecia",
                "market_value" => 1.00,
                "fav_foot" => "Sinistro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66cf4c0a/HMHNL.png?webp&q=100&ch=840&size=540x-",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Tommaso",
                "last_name" => "Pobega",
                "date_of_birth" => '1999-07-15',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 10.00,
                "fav_foot" => "Sinistro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66db1bdd/PBGMMS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Giovanni",
                "last_name" => "Fabbian",
                "date_of_birth" => '2003-01-14',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 13.00,
                "fav_foot" => "Destro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/66cf4bfd/FBBVNN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Riccardo",
                "last_name" => "Orsolini",
                "date_of_birth" => '1997-01-24',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 16.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf4bdf/P-557.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Santiago",
                "last_name" => "Castro",
                "date_of_birth" => '2004-09-18',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 25.00,
                "fav_foot" => "Destro",
                "height" => "1.79",
                "img" => "https://img.legaseriea.it/vimages/66cf4be9/CSTNTG.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            [
                "first_name" => "Dan",
                "last_name" => "Ndoye",
                "date_of_birth" => '2000-10-25',
                "role" => "Attaccante",
                "nationality" => "Svizzera",
                "market_value" => 25.00,
                "fav_foot" => "Destro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/66cf4c05/NDOYED.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 7,
                "coach_id" => 1,
            ],
            // CAGLIARI
            [
                "first_name" => "Giuseppe",
                "last_name" => "Ciocci",
                "date_of_birth" => '2002-01-24',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 0.10,
                "fav_foot" => "Destro",
                "height" => "1.93",
                "img" => "https://img.legaseriea.it/vimages/66cf5a48/CCCSPP.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            [
                "first_name" => "Nadir",
                "last_name" => "Zortea",
                "date_of_birth" => '1999-06-19',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 3.00,
                "fav_foot" => "Destro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66cf5a4d/ZRTNDR.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            [
                "first_name" => "Tommaso",
                "last_name" => "Augello",
                "date_of_birth" => '1994-08-30',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 1.80,
                "fav_foot" => "Sinistro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66cf5a31/GLLMMS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            [
                "first_name" => "Razvan",
                "last_name" => "Marin",
                "date_of_birth" => '1996-05-23',
                "role" => "Centrocampista",
                "nationality" => "Romania",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66cf5a39/PWPZH.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            [
                "first_name" => "Roberto",
                "last_name" => "Piccoli",
                "date_of_birth" => '2001-01-27',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66cf5a2e/PCCBRT.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            [
                "first_name" => "Zito",
                "last_name" => "Luvumbo",
                "date_of_birth" => '2002-03-09',
                "role" => "Attaccante",
                "nationality" => "Angola",
                "market_value" => 7.00,
                "fav_foot" => "Sinistro",
                "height" => "1.71",
                "img" => "https://img.legaseriea.it/vimages/66cf5a30/LVMBZT.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 11,
                "coach_id" => 2,
            ],
            // COMO
            [
                "first_name" => "Pepe",
                "last_name" => "Reina",
                "date_of_birth" => '1982-08-31',
                "role" => "Portiere",
                "nationality" => "Spagna",
                "market_value" => 0.60,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66db1ca7/RNAJS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Alberto",
                "last_name" => "Dossena",
                "date_of_birth" => '1998-10-13',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.95",
                "img" => "https://img.legaseriea.it/vimages/66cf5a83/P-527.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Edoardo",
                "last_name" => "Goldaniga",
                "date_of_birth" => '1993-11-02',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 1.20,
                "fav_foot" => "Destro",
                "height" => "1.93",
                "img" => "https://img.legaseriea.it/vimages/66cf5a70/CNSZH.png?webp&q=100&ch=840&size=276x-",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Nico",
                "last_name" => "Paz",
                "date_of_birth" => '2004-09-08',
                "role" => "Centrocampista",
                "nationality" => "Argentina",
                "market_value" => 20.00,
                "fav_foot" => "Sinistro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/671915f1/PAZNIC.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Sergi",
                "last_name" => "Roberto",
                "date_of_birth" => '1992-02-07',
                "role" => "Centrocampista",
                "nationality" => "Spagna",
                "market_value" => 2.00,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66db1ca2/RBRSR.png?webp&q=100&ch=840&size=379.5x-",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Lucas",
                "last_name" => "Da Cunha",
                "date_of_birth" => '2001-06-09',
                "role" => "Centrocampista",
                "nationality" => "Francia",
                "market_value" => 6.00,
                "fav_foot" => "Sinistro",
                "height" => "1.74",
                "img" => "https://img.legaseriea.it/vimages/66cf5a6e/DCNLCS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Patrick",
                "last_name" => "Cutrone",
                "date_of_birth" => '1998-01-03',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf5a9b/QBNBW.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            [
                "first_name" => "Gabriel",
                "last_name" => "Strefezza",
                "date_of_birth" => '1997-04-18',
                "role" => "Attaccante",
                "nationality" => "Brasile",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.68",
                "img" => "https://img.legaseriea.it/vimages/66cf5a67/STRBRL.png?webp&q=100&ch=840&size=273x-",
                "team_id" => 9,
                "coach_id" => 3,
            ],
            // EMPOLI
            [
                "first_name" => "Devis",
                "last_name" => "Vaquez",
                "date_of_birth" => '1998-05-12',
                "role" => "Portiere",
                "nationality" => "Colombia",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.95",
                "img" => "https://img.legaseriea.it/vimages/66cf59ea/VSQDVS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Mattia",
                "last_name" => "De Sciglio",
                "date_of_birth" => '1992-10-28',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 1.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66def3c6/DSCMT.png?webp&q=100&ch=840&size=457.5x-",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Ardian",
                "last_name" => "Ismajli",
                "date_of_birth" => '1992-10-28',
                "role" => "Difensore",
                "nationality" => "Albania",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66cf5a0d/SMJRDN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Jacopo",
                "last_name" => "Fazzini",
                "date_of_birth" => '2003-03-16',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66cf59e9/FZZJCP.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Liam",
                "last_name" => "Henderson",
                "date_of_birth" => '1996-04-25',
                "role" => "Centrocampista",
                "nationality" => "Scozia",
                "market_value" => 1.40,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf5a1d/HNDLM.png?webp&q=100&ch=840&size=297x-",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Nicolas",
                "last_name" => "Haas",
                "date_of_birth" => '1996-01-23',
                "role" => "Centrocampista",
                "nationality" => "Svizzera",
                "market_value" => 0.70,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66cf5a09/HSNCLS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Lorenzo",
                "last_name" => "Colombo",
                "date_of_birth" => '2002-03-08',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 6.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf5a14/CLMRN1.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            [
                "first_name" => "Sebastiano",
                "last_name" => "Esposito",
                "date_of_birth" => '2002-07-02',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf59fc/SPSSTN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 17,
                "coach_id" => 4,
            ],
            // FIORENTINA
            [
                "first_name" => "David",
                "last_name" => "De Gea",
                "date_of_birth" => '1990-11-07',
                "role" => "Portiere",
                "nationality" => "Spagna",
                "market_value" => 5.00,
                "fav_foot" => "Destro",
                "height" => "1.92",
                "img" => "https://img.legaseriea.it/vimages/671915c9/DGDVD.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Robin",
                "last_name" => "Gosens",
                "date_of_birth" => '1994-07-05',
                "role" => "Difensore",
                "nationality" => "Germania",
                "market_value" => 8.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/671915dc/GSNRBN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Fabiano",
                "last_name" => "Parisi",
                "date_of_birth" => '2000-11-09',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 5.00,
                "fav_foot" => "Sinistro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66d0590c/PRSFBN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Edoardo",
                "last_name" => "Bove",
                "date_of_birth" => '2002-05-16',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 14.00,
                "fav_foot" => "Destro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/66e2a1f7/BOVEED.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Andrea",
                "last_name" => "Colpani",
                "date_of_birth" => '1999-05-11',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 16.00,
                "fav_foot" => "Sinistro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/66d05907/CLPNDR.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Moise",
                "last_name" => "Kean",
                "date_of_birth" => '2000-02-28',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 30.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d05901/GQQMS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Rolando",
                "last_name" => "Mandragora",
                "date_of_birth" => '1997-06-29',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 30.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d05902/MNDRL.png?webp&q=100&ch=840&size=339x-",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            [
                "first_name" => "Albert",
                "last_name" => "Gudmundsson",
                "date_of_birth" => '1997-06-15',
                "role" => "Attaccante",
                "nationality" => "Islanda",
                "market_value" => 28.00,
                "fav_foot" => "Destro",
                "height" => "1.77",
                "img" => "https://img.legaseriea.it/vimages/671915d7/GDMBRT.png?webp&q=100&ch=840&size=376.5x-",
                "team_id" => 8,
                "coach_id" => 5,
            ],
            // GENOA
            [
                "first_name" => "Nicola",
                "last_name" => "Leali",
                "date_of_birth" => '1993-02-17',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 0.80,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66db1c55/LLNCL.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Aaron",
                "last_name" => "Martin",
                "date_of_birth" => '1997-04-22',
                "role" => "Difensore",
                "nationality" => "Spagna",
                "market_value" => 5.00,
                "fav_foot" => "Sinistro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66d05941/MRTNRN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Koni",
                "last_name" => "De Winter",
                "date_of_birth" => '2002-06-12',
                "role" => "Difensore",
                "nationality" => "Belgio",
                "market_value" => 12.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66d0592f/DWNRKN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Ruslan",
                "last_name" => "Malinovskyi",
                "date_of_birth" => '1993-05-04',
                "role" => "Centrocampista",
                "nationality" => "Ucraina",
                "market_value" => 3.50,
                "fav_foot" => "Sinistro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/66d05922/XKPXG.png?webp&q=100&ch=840&size=552x-",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Morten",
                "last_name" => "Thorsby",
                "date_of_birth" => '1996-05-05',
                "role" => "Centrocampista",
                "nationality" => "Norvegia",
                "market_value" => 3.50,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66d05922/THRRTN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Fabio",
                "last_name" => "Miretti",
                "date_of_birth" => '2003-08-03',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 12.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66dee5bd/MRTTFB.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Andrea",
                "last_name" => "Pinamonti",
                "date_of_birth" => '1999-05-19',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 16.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d05952/QVBNF.png?webp&q=100&ch=840&size=453x-",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            [
                "first_name" => "Caleb",
                "last_name" => "Ekuban",
                "date_of_birth" => '1994-03-23',
                "role" => "Attaccante",
                "nationality" => "Ghana",
                "market_value" => 1.50,
                "fav_foot" => "Destro",
                "height" => "1.82",
                "img" => "https://img.legaseriea.it/vimages/66d05943/KBNCL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 19,
                "coach_id" => 6,
            ],
            // HELLAS VERONA
            [
                "first_name" => "Lorenzo",
                "last_name" => "Montipò",
                "date_of_birth" => '1996-02-20',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 3.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/6749cabd/c7fky0h6gi7wmibnv2tzf6mz9.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Davide",
                "last_name" => "Faraoni",
                "date_of_birth" => '1991-10-25',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 3.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/6749da90/68etig279gs3btjb7fv6rvfth.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Jackson",
                "last_name" => "Tchatchoua",
                "date_of_birth" => '2001-09-14',
                "role" => "Difensore",
                "nationality" => "Camerun",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/6749db66/39bcswfqnpa07b4afevezejo4.png?webp&q=100&ch=840&size=319.5x-",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Abdou",
                "last_name" => "Harroui",
                "date_of_birth" => '1998-01-13',
                "role" => "Centrocampista",
                "nationality" => "Marocco",
                "market_value" => 2.50,
                "fav_foot" => "Entrambi",
                "height" => "1.82",
                "img" => "https://img.legaseriea.it/vimages/6749dc54/74o97lnqpku6m9svks66qbend.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Darko",
                "last_name" => "Lazović",
                "date_of_birth" => '1990-09-15',
                "role" => "Centrocampista",
                "nationality" => "Serbia",
                "market_value" => 1.50,
                "fav_foot" => "Sinistro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/6749cd56/bo98qzo4gu0npm4pewc25ovyt.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Amin",
                "last_name" => "Sarr",
                "date_of_birth" => '2001-03-11',
                "role" => "Attaccante",
                "nationality" => "Svezia",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/6749e749/amvonu36at4dg7ksi1ioczi3u.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Dailon",
                "last_name" => "Rocha Livramento",
                "date_of_birth" => '2001-04-04',
                "role" => "Attaccante",
                "nationality" => "Capo Verde",
                "market_value" => 0.80,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/6749ca59/1dljhkcvmodqq9u1w8iv145m2.png?webp&q=100&ch=840&size=793.5x-",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            [
                "first_name" => "Alphadjo",
                "last_name" => "Cissè",
                "date_of_birth" => '2006-10-22',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 1.40,
                "fav_foot" => "Destro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/6749e9ab/498kxii7w64hmki575xdur28k.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 12,
                "coach_id" => 19,
            ],
            // INTER
            [
                "first_name" => "Yann",
                "last_name" => "Sommer",
                "date_of_birth" => '1988-12-17',
                "role" => "Portiere",
                "nationality" => "Svizzera",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66db1c6c/SMMYN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Federico",
                "last_name" => "Dimarco",
                "date_of_birth" => '1997-11-10',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 60.00,
                "fav_foot" => "Sinistro",
                "height" => "1.75",
                "img" => "https://img.legaseriea.it/vimages/66cf305e/NWFZS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Denzel",
                "last_name" => "Dumfries",
                "date_of_birth" => '1996-04-18',
                "role" => "Difensore",
                "nationality" => "Olanda",
                "market_value" => 20.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf305d/DMFNZL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Nicolò",
                "last_name" => "Barella",
                "date_of_birth" => '1997-02-07',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 80.00,
                "fav_foot" => "Destro",
                "height" => "1.75",
                "img" => "https://img.legaseriea.it/vimages/66cf3057/BRLNC.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Henrikh",
                "last_name" => "Mkhitaryan",
                "date_of_birth" => '1989-01-21',
                "role" => "Centrocampista",
                "nationality" => "Armenia",
                "market_value" => 5.00,
                "fav_foot" => "Entrambi",
                "height" => "1.77",
                "img" => "https://img.legaseriea.it/vimages/66cf306d/MKMKS.png?webp&q=100&ch=840&size=303x-",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Hakan",
                "last_name" => "Çalhanoğlu",
                "date_of_birth" => '1994-02-08',
                "role" => "Centrocampista",
                "nationality" => "Turchia",
                "market_value" => 40.00,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66cf304f/CLHHK.png?webp&q=100&ch=840&size=325.5x-",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Lautaro",
                "last_name" => "Martinez",
                "date_of_birth" => '1997-08-22',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 100.00,
                "fav_foot" => "Destro",
                "height" => "1.74",
                "img" => "https://img.legaseriea.it/vimages/66cf3058/MRTLTR.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            [
                "first_name" => "Marcus",
                "last_name" => "Thuram",
                "date_of_birth" => '1997-08-06',
                "role" => "Attaccante",
                "nationality" => "Francia",
                "market_value" => 75.00,
                "fav_foot" => "Destro",
                "height" => "1.92",
                "img" => "https://img.legaseriea.it/vimages/66cf3033/THRRCS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 3,
                "coach_id" => 7,
            ],
            // JUVENTUS
            [
                "first_name" => "Michele",
                "last_name" => "Di Gregorio",
                "date_of_birth" => '1997-07-27',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 18.00,
                "fav_foot" => "Destro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66d05730/ZMPGT.png?webp&q=100&ch=840&size=528x-",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Gleison",
                "last_name" => "Bremer",
                "date_of_birth" => '1997-03-18',
                "role" => "Difensore",
                "nationality" => "Brasile",
                "market_value" => 60.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66d05708/BRMRX.png?webp&q=100&ch=840&size=-x396",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Federico",
                "last_name" => "Gatti",
                "date_of_birth" => '1998-06-24',
                "role" => "Difensore",
                "nationality" => "Italiano",
                "market_value" => 25.00,
                "fav_foot" => "Destro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66d0572b/GTTDRC.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Khephren",
                "last_name" => "Thuram",
                "date_of_birth" => '2001-03-26',
                "role" => "Centrocampista",
                "nationality" => "Francia",
                "market_value" => 35.00,
                "fav_foot" => "Destro",
                "height" => "1.92",
                "img" => "https://img.legaseriea.it/vimages/66d05721/THRHRN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Manuel",
                "last_name" => "Locatelli",
                "date_of_birth" => '1998-01-08',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 28.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d05742/LCTMN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Weston",
                "last_name" => "McKennie",
                "date_of_birth" => '1998-08-28',
                "role" => "Centrocampista",
                "nationality" => "Stati Uniti",
                "market_value" => 24.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d0572b/MCKSTN.png?webp&q=100&ch=840&size=270x-",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Francisco",
                "last_name" => "Conceição",
                "date_of_birth" => '2002-12-14',
                "role" => "Attaccante",
                "nationality" => "Portogallo",
                "market_value" => 36.00,
                "fav_foot" => "Sinistro",
                "height" => "1.70",
                "img" => "https://img.legaseriea.it/vimages/66db1b5b/CNCFN.png?webp&q=100&ch=840&size=277.5x-",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            [
                "first_name" => "Kenan",
                "last_name" => "Yldiz",
                "date_of_birth" => '2005-05-04',
                "role" => "Attaccante",
                "nationality" => "Turchia",
                "market_value" => 45.00,
                "fav_foot" => "Entrambi",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66d0571b/YLDKNN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 1,
                "coach_id" => 8,
            ],
            // LAZIO
            [
                "first_name" => "Ivan",
                "last_name" => "Provedel",
                "date_of_birth" => '1994-03-17',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 14.00,
                "fav_foot" => "Destro",
                "height" => "1.94",
                "img" => "https://img.legaseriea.it/vimages/66d057db/PRDVN.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            [
                "first_name" => "Nuno",
                "last_name" => "Tavares",
                "date_of_birth" => '2000-01-26',
                "role" => "Difensore",
                "nationality" => "Portogallo",
                "market_value" => 25.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d05805/NNTVRS.png?webp&q=100&ch=840&size=628.5x-",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            [
                "first_name" => "Adam",
                "last_name" => "Marusic",
                "date_of_birth" => '1992-10-17',
                "role" => "Difensore",
                "nationality" => "Montenegro",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d057de/MRSCDM.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            [
                "first_name" => "Mattia",
                "last_name" => "Zaccagni",
                "date_of_birth" => '1995-06-16',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 20.00,
                "fav_foot" => "Destro",
                "height" => "1.77",
                "img" => "https://img.legaseriea.it/vimages/66d057cc/BTMNG.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            [
                "first_name" => "Taty",
                "last_name" => "Castellanos",
                "date_of_birth" => '1998-10-03',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 20.00,
                "fav_foot" => "Destro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66d057ef/CSTTTY.png?webp&q=100&ch=840&size=591x-",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            [
                "first_name" => "Boulaye",
                "last_name" => "Dia",
                "date_of_birth" => '1996-11-16',
                "role" => "Attaccante",
                "nationality" => "Senegal",
                "market_value" => 15.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66d057f0/DIABOU.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 15,
                "coach_id" => 9,
            ],
            // LECCE
            [
                "first_name" => "Wladimiro",
                "last_name" => "Falcone",
                "date_of_birth" => '1995-04-12',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.95",
                "img" => "https://img.legaseriea.it/vimages/66d0589b/FLCWL.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            [
                "first_name" => "Federico",
                "last_name" => "Baschirotto",
                "date_of_birth" => '1996-09-20',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 5.00,
                "fav_foot" => "Destro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66d0587c/BSCDRC.png?webp&q=100&ch=840&size=574.5x-",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            [
                "first_name" => "Antonino",
                "last_name" => "Gallo",
                "date_of_birth" => '2000-01-05',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 5.50,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d05862/GLLTNN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            [
                "first_name" => "Lassana",
                "last_name" => "coulibaly",
                "date_of_birth" => '1996-04-10',
                "role" => "Centrocampista",
                "nationality" => "Mali",
                "market_value" => 2.50,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d0586f/WXPLR.png?webp&q=100&ch=840&size=453x-",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            [
                "first_name" => "Nikola",
                "last_name" => "Krstović",
                "date_of_birth" => '2000-04-05',
                "role" => "Attaccante",
                "nationality" => "Montenegro",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d05884/KRSNKL.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            [
                "first_name" => "Santiago",
                "last_name" => "Pierotti",
                "date_of_birth" => '2001-04-03',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 2.50,
                "fav_foot" => "Destro",
                "height" => "1.89",
                "img" => "https://img.legaseriea.it/vimages/66d0587a/PRTNTG.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 14,
                "coach_id" => 13,
            ],
            // MILAN
            [
                "first_name" => "Mike",
                "last_name" => "Maignan",
                "date_of_birth" => '1995-07-03',
                "role" => "Portiere",
                "nationality" => "Francia",
                "market_value" => 35.00,
                "fav_foot" => "Destro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66cf21da/MGNMK.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            [
                "first_name" => "Theo",
                "last_name" => "Hernández",
                "date_of_birth" => '1997-10-06',
                "role" => "Difensore",
                "nationality" => "Francia",
                "market_value" => 50.00,
                "fav_foot" => "Sinistro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/67191596/HRNZTH.png?webp&q=100&ch=840&size=306x-",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            [
                "first_name" => "Fikayo",
                "last_name" => "Tomori",
                "date_of_birth" => '1997-12-19',
                "role" => "Difensore",
                "nationality" => "Inghilterra",
                "market_value" => 22.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66cf21d0/TMRFKY.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            [
                "first_name" => "Tijjani",
                "last_name" => "Reijnders",
                "date_of_birth" => '1998-07-29',
                "role" => "Centrocampista",
                "nationality" => "Olanda",
                "market_value" => 50.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66cf21cb/RJNJJN.png?webp&q=100&ch=840&size=271.5x-",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            [
                "first_name" => "Youssouf",
                "last_name" => "Fofana",
                "date_of_birth" => '1999-01-10',
                "role" => "Centrocampista",
                "nationality" => "Francia",
                "market_value" => 30.00,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66db1b7a/FFNSSF.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            [
                "first_name" => "Rafael",
                "last_name" => "Leão",
                "date_of_birth" => '1999-06-10',
                "role" => "Attaccante",
                "nationality" => "Portogallo",
                "market_value" => 75.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf21b3/LEAORA.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 2,
                "coach_id" => 10,
            ],
            // MONZA
            [
                "first_name" => "Stefano",
                "last_name" => "Turati",
                "date_of_birth" => '2001-09-05',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 7.50,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66cf300b/TRTTFN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            [
                "first_name" => "Luca",
                "last_name" => "Caldirola",
                "date_of_birth" => '1991-02-01',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 1.00,
                "fav_foot" => "Sinistro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/66cf3005/CLDLC.png?webp&q=100&ch=840&size=294x-",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            [
                "first_name" => "Luca",
                "last_name" => "Izzo",
                "date_of_birth" => '1992-03-02',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 2.50,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66cf3005/CLDLC.png?webp&q=100&ch=840&size=294x-",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            [
                "first_name" => "Matteo",
                "last_name" => "Pessina",
                "date_of_birth" => '1997-04-21',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 12.00,
                "fav_foot" => "Sinistro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66cf2fed/CVGHT.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            [
                "first_name" => "Dany",
                "last_name" => "Mota",
                "date_of_birth" => '1998-08-02',
                "role" => "Attaccante",
                "nationality" => "Portogallo",
                "market_value" => 5.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66cf3013/P-860.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            [
                "first_name" => "Patrick",
                "last_name" => "Ciurria",
                "date_of_birth" => '1995-02-09',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 3.00,
                "fav_foot" => "Entrambi",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66cf3000/ZZBHB.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 13,
                "coach_id" => 14,
            ],
            // NAPOLI
            [
                "first_name" => "Alex",
                "last_name" => "Meret",
                "date_of_birth" => '1997-03-22',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 12.00,
                "fav_foot" => "Sinistro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66db1c0b/XXNLW.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            [
                "first_name" => "Giovanni",
                "last_name" => "Di Lorenzo",
                "date_of_birth" => '1993-08-04',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 15.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d058a9/DLRG9.png?webp&q=100&ch=840&size=306x-",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            [
                "first_name" => "Alessandro",
                "last_name" => "Buongiorno",
                "date_of_birth" => '1999-06-06',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 45.00,
                "fav_foot" => "Sinistro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66d058b1/BNGNDR.png?webp&q=100&ch=840&size=321x-",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            [
                "first_name" => "Stanislav",
                "last_name" => "Lobotka",
                "date_of_birth" => '1994-11-25',
                "role" => "Centrocampista",
                "nationality" => "Slovacchia",
                "market_value" => 28.00,
                "fav_foot" => "Destro",
                "height" => "1.68",
                "img" => "https://img.legaseriea.it/vimages/66d058c5/LBTST.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            [
                "first_name" => "Frank",
                "last_name" => "Anguissa",
                "date_of_birth" => '1995-11-16',
                "role" => "Centrocampista",
                "nationality" => "Camerun",
                "market_value" => 27.00,
                "fav_foot" => "Destro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/66d058d6/RGRLW.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            [
                "first_name" => "Romelu",
                "last_name" => "Lukaku",
                "date_of_birth" => '1993-05-13',
                "role" => "Attaccante",
                "nationality" => "Belgio",
                "market_value" => 25.00,
                "fav_foot" => "Sinistro",
                "height" => "1.91",
                "img" => "https://img.legaseriea.it/vimages/66db1c03/LKKRM.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 4,
                "coach_id" => 11,
            ],
            // PARMA
            [
                "first_name" => "Edoardo",
                "last_name" => "Corvi",
                "date_of_birth" => '2001-03-23',
                "role" => "Portiere",
                "nationality" => "Italia",
                "market_value" => 0.35,
                "fav_foot" => "Destro",
                "height" => "1.87",
                "img" => "https://img.legaseriea.it/vimages/66d0578d/CRVDRD.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            [
                "first_name" => "Enrico",
                "last_name" => "Delprato",
                "date_of_birth" => '1999-11-10',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d057ca/DLPNRC.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            [
                "first_name" => "Emanuele",
                "last_name" => "Valeri",
                "date_of_birth" => '1998-12-07',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 3.00,
                "fav_foot" => "Sinistro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66d0578b/VLRMN1.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            [
                "first_name" => "Mateusz",
                "last_name" => "Kowalski",
                "date_of_birth" => '2005-07-21',
                "role" => "Centrocampista",
                "nationality" => "Polonia",
                "market_value" => 0.30,
                "fav_foot" => "Destro",
                "height" => "1.97",
                "img" => "https://img.legaseriea.it/vimages/66d491da/KWLTSZ.png?webp&q=100&ch=840&size=267x-",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            [
                "first_name" => "Ange-Yoan",
                "last_name" => "Bonny",
                "date_of_birth" => '2003-10-25',
                "role" => "Attaccante",
                "nationality" => "Francia",
                "market_value" => 20.00,
                "fav_foot" => "Destro",
                "height" => "1.89",
                "img" => "https://img.legaseriea.it/vimages/66d0578b/BNN-YN.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            [
                "first_name" => "Dennis",
                "last_name" => "Man",
                "date_of_birth" => '1998-08-26',
                "role" => "Attaccante",
                "nationality" => "Romania",
                "market_value" => 17.00,
                "fav_foot" => "Sinistro",
                "height" => "1.83",
                "img" => "https://img.legaseriea.it/vimages/66d057ca/MNDNNS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 18,
                "coach_id" => 15,
            ],
            // ROMA
            [
                "first_name" => "Mile",
                "last_name" => "Svilar",
                "date_of_birth" => '1999-08-27',
                "role" => "Portiere",
                "nationality" => "Serbia",
                "market_value" => 14.00,
                "fav_foot" => "Destro",
                "height" => "1.89",
                "img" => "https://img.legaseriea.it/vimages/66cf21e4/SVLRML.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            [
                "first_name" => "Gianluca",
                "last_name" => "Mancini",
                "date_of_birth" => '1996-04-17',
                "role" => "Difensore",
                "nationality" => "Italia",
                "market_value" => 18.00,
                "fav_foot" => "Destro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66cf21e2/MNCGW.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            [
                "first_name" => "Lorenzo",
                "last_name" => "Pellegrini",
                "date_of_birth" => '1996-06-19',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 14.00,
                "fav_foot" => "Destro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/66cf21f6/PGWCM.png?webp&q=100&ch=840&size=301.5x-",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            [
                "first_name" => "Bryan",
                "last_name" => "Cristante",
                "date_of_birth" => '1995-03-03',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 12.00,
                "fav_foot" => "Destro",
                "height" => "1.86",
                "img" => "https://img.legaseriea.it/vimages/66cf21f4/LKXHL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            [
                "first_name" => "Paulo",
                "last_name" => "Dybala",
                "date_of_birth" => '1993-11-15',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 8.00,
                "fav_foot" => "Sinistro",
                "height" => "1.77",
                "img" => "https://img.legaseriea.it/vimages/66cf2202/DBLPL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            [
                "first_name" => "Matías",
                "last_name" => "Soulé",
                "date_of_birth" => '2003-04-15',
                "role" => "Attaccante",
                "nationality" => "Argentina",
                "market_value" => 22.00,
                "fav_foot" => "Sinistro",
                "height" => "1.82",
                "img" => "https://img.legaseriea.it/vimages/66cf2211/SLMMTS.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 6,
                "coach_id" => 16,
            ],
            // TORINO
            [
                "first_name" => "Vanja",
                "last_name" => "Milinković-Savić",
                "date_of_birth" => '1997-02-20',
                "role" => "Portiere",
                "nationality" => "Serbia",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "2.02",
                "img" => "https://img.legaseriea.it/vimages/66db1c87/MLNVNJ.png?webp&q=100&ch=840&size=471x-",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Guillermo",
                "last_name" => "Maripán",
                "date_of_birth" => '1994-05-06',
                "role" => "Difensore",
                "nationality" => "Cile",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.93",
                "img" => "https://img.legaseriea.it/vimages/66db1c78/MRPLRM.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Valentino",
                "last_name" => "Lazaro",
                "date_of_birth" => '1996-03-24',
                "role" => "Difensore",
                "nationality" => "Austria",
                "market_value" => 3.50,
                "fav_foot" => "Destro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/66d059fc/LZRVL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Samuele",
                "last_name" => "Ricci",
                "date_of_birth" => '2001-08-21',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 28.00,
                "fav_foot" => "Destro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/66d059c0/RCCSML.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Nikola",
                "last_name" => "Vlašić",
                "date_of_birth" => '1997-10-04',
                "role" => "Centrocampista",
                "nationality" => "Croazia",
                "market_value" => 7.00,
                "fav_foot" => "Destro",
                "height" => "1.79",
                "img" => "https://img.legaseriea.it/vimages/66d059e1/FRBBK.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Ché",
                "last_name" => "Adams",
                "date_of_birth" => '1996-07-13',
                "role" => "Attaccante",
                "nationality" => "Scozia",
                "market_value" => 15.00,
                "fav_foot" => "Destro",
                "height" => "1.79",
                "img" => "https://img.legaseriea.it/vimages/66d059d9/ADMCX.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Antonio",
                "last_name" => "Sanabria",
                "date_of_birth" => '1996-03-04',
                "role" => "Attaccante",
                "nationality" => "Paraguay",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66d059d4/SNBNT.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            [
                "first_name" => "Duvan",
                "last_name" => "Zapata",
                "date_of_birth" => '1991-03-01',
                "role" => "Attaccante",
                "nationality" => "Colombia",
                "market_value" => 4.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66d059d1/ZPTDV.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 10,
                "coach_id" => 17,
            ],
            // UDINESE
            [
                "first_name" => "Maduka",
                "last_name" => "Okoye",
                "date_of_birth" => '1999-08-28',
                "role" => "Portiere",
                "nationality" => "Nigeria",
                "market_value" => 7.50,
                "fav_foot" => "Destro",
                "height" => "1.98",
                "img" => "https://img.legaseriea.it/vimages/66d05974/OKOYEM.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Kingsley",
                "last_name" => "Ehizibue",
                "date_of_birth" => '1995-05-25',
                "role" => "Difensore",
                "nationality" => "Olanda",
                "market_value" => 3.00,
                "fav_foot" => "Destro",
                "height" => "1.89",
                "img" => "https://img.legaseriea.it/vimages/66d0597a/HZBSLY.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Oumar",
                "last_name" => "Solet",
                "date_of_birth" => '2000-02-07',
                "role" => "Difensore",
                "nationality" => "Francia",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "1.92",
                "img" => "https://img.legaseriea.it/vimages/67b5bdb2/cet0tgjv82l6ao07ij1ylgp9l.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Sandi",
                "last_name" => "Lovrić",
                "date_of_birth" => '1998-03-28',
                "role" => "Centrocampista",
                "nationality" => "Slovenia",
                "market_value" => 8.00,
                "fav_foot" => "Destro",
                "height" => "1.80",
                "img" => "https://img.legaseriea.it/vimages/66d059a7/LVRSND.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Jurgen",
                "last_name" => "Ekkelenkamp",
                "date_of_birth" => '2000-04-05',
                "role" => "Centrocampista",
                "nationality" => "Olanda",
                "market_value" => 5.50,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/66d05971/KKLRGN.png?webp&q=100&ch=840&size=352.5x-",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Lorenzo",
                "last_name" => "Lucca",
                "date_of_birth" => '2000-09-10',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 18.00,
                "fav_foot" => "Destro",
                "height" => "2.01",
                "img" => "https://img.legaseriea.it/vimages/66d059a0/LCCRN1.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Florian",
                "last_name" => "Thauvin",
                "date_of_birth" => '1993-01-26',
                "role" => "Attaccante",
                "nationality" => "Francia",
                "market_value" => 5.00,
                "fav_foot" => "Sinistro",
                "height" => "1.81",
                "img" => "https://img.legaseriea.it/vimages/66d05977/THVFL.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            [
                "first_name" => "Alexis",
                "last_name" => "Sanchez",
                "date_of_birth" => '1988-12-19',
                "role" => "Attaccante",
                "nationality" => "Cile",
                "market_value" => 2.00,
                "fav_foot" => "Destro",
                "height" => "1.69",
                "img" => "https://img.legaseriea.it/vimages/66d0596c/SNCLL.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 16,
                "coach_id" => 18,
            ],
            // VENEZIA
            [
                "first_name" => "Jesse",
                "last_name" => "Joronen",
                "date_of_birth" => '1993-03-21',
                "role" => "Portiere",
                "nationality" => "Finlandia",
                "market_value" => 1.00,
                "fav_foot" => "Destro",
                "height" => "1.97",
                "img" => "https://img.legaseriea.it/vimages/66d0577e/JRNJSS.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Jay",
                "last_name" => "Idzes",
                "date_of_birth" => '2000-06-02',
                "role" => "Difensore",
                "nationality" => "Indonesia",
                "market_value" => 3.00,
                "fav_foot" => "Destro",
                "height" => "1.90",
                "img" => "https://img.legaseriea.it/vimages/66d05786/IDZESJ.png?webp&q=100&ch=840&size=-x444",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Joel",
                "last_name" => "Schingtienne",
                "date_of_birth" => '2002-08-14',
                "role" => "Difensore",
                "nationality" => "Belgio",
                "market_value" => 2.00,
                "fav_foot" => "Destro",
                "height" => "1.88",
                "img" => "https://img.legaseriea.it/vimages/6719157a/SCHGJ.png?webp&q=100&ch=840&size=604.5x-",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Hans",
                "last_name" => "Nicolussi Caviglia",
                "date_of_birth" => '2000-06-18',
                "role" => "Centrocampista",
                "nationality" => "Italia",
                "market_value" => 6.00,
                "fav_foot" => "Destro",
                "height" => "1.84",
                "img" => "https://img.legaseriea.it/vimages/67191580/NCLHNS.png?webp&q=100&ch=840&size=885x-",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Mikael",
                "last_name" => "Ellertsson",
                "date_of_birth" => '2002-03-11',
                "role" => "Centrocampista",
                "nationality" => "Islanda",
                "market_value" => 2.80,
                "fav_foot" => "Sinistro",
                "height" => "1.82",
                "img" => "https://img.legaseriea.it/vimages/66d05773/LLRMKL.png?webp&q=100&ch=840&size=531x-",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Alfred",
                "last_name" => "Duncan",
                "date_of_birth" => '1993-03-10',
                "role" => "Centrocampista",
                "nationality" => "Ghana",
                "market_value" => 2.50,
                "fav_foot" => "Sinistro",
                "height" => "1.78",
                "img" => "https://img.legaseriea.it/vimages/66d0576e/DNCSP.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Christian",
                "last_name" => " Gytkjær",
                "date_of_birth" => '1990-05-06',
                "role" => "Attaccante",
                "nationality" => "Danimarca",
                "market_value" => 0.70,
                "fav_foot" => "Destro",
                "height" => "1.85",
                "img" => "https://img.legaseriea.it/vimages/66d05766/GYTSTN.png?webp&q=100&ch=840&size=459x-",
                "team_id" => 20,
                "coach_id" => 12,
            ],
            [
                "first_name" => "Gaetano",
                "last_name" => " Oristanio",
                "date_of_birth" => '2002-09-28',
                "role" => "Attaccante",
                "nationality" => "Italia",
                "market_value" => 6.50,
                "fav_foot" => "Sinistro",
                "height" => "1.74",
                "img" => "https://img.legaseriea.it/vimages/66d05781/RSTTNP.png?webp&q=100&ch=840&size=-x265.5",
                "team_id" => 20,
                "coach_id" => 12,
            ],
        ];
        foreach ($players as $player) {
            Player::create($player);
        }
    }
}
